name: cactus_sync_client_gen
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  graphql: ^5.0.0-nullsafety.4
  build: ^2.0.1
  path: ^1.7.0
  indent: ^2.0.0
  code_builder: ^4.0.0

dev_dependencies:
  build_runner: ^2.0.1
  build_web_compilers: ^3.0.0
  build_config: ^1.0.0
  lint: ^1.5.3
  test: ^1.14.4
  riverpod: ^0.14.0
